import Image from 'next/image';
import { CartPage } from '../src/components/home/cart-page';
import Link from 'next/link';
import Head from 'next/head';
import React from "react";

export default function CartPageo({ ev }) {

  return (

    <div className='cart'>
      <Head>
        <title>Cart app</title>
        <meta name="description" content="Generated by create next app" />


      </Head>
      {/* <h1>Hello {location.state.id} and welcome to the home</h1> */}
      <CartPage data={ev} />

    </div>
  );
}


// const CartPage = () => {
//   return <Cart />;
// };

// export default CartPage;

export async function getServerSideProps() {


  const { allEvents } = await import('../data/data.json')

  return {
    props: {
      ev: allEvents,
    },
  };
}
